'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, Plus } from 'lucide-react';
import { PainelShell } from '../components/PainelShell';

type Usuario = { id: string; nome: string; email: string; perfil: 'OPERADOR' | 'ADMINISTRADOR'; ativo: boolean; };
const initialForm = { nome: '', email: '', senha: '', perfil: 'OPERADOR' as 'OPERADOR' | 'ADMINISTRADOR' };

export default function UsuariosPage() {
  const [users, setUsers] = useState<Usuario[]>([]);
  const [form, setForm] = useState(initialForm);
  const [showForm, setShowForm] = useState(false);
  const [message, setMessage] = useState('');
  async function loadUsers() { const response = await fetch('/api/usuarios'); if (response.status === 403) { setMessage('Apenas administradores podem acessar esta tela.'); return; } const data = await response.json(); setUsers(data.usuarios || []); }
  useEffect(() => { loadUsers(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setMessage(''); const response = await fetch('/api/usuarios', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setMessage(data.erro || 'Não foi possível criar o usuário.'); return; } setForm(initialForm); setShowForm(false); setMessage('Usuário criado com sucesso.'); await loadUsers(); }
  async function toggle(user: Usuario) { const response = await fetch('/api/usuarios', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: user.id, ativo: !user.ativo }) }); const data = await response.json(); if (response.ok) setUsers(current => current.map(item => item.id === data.id ? data : item)); else setMessage(data.erro); }
  return <PainelShell active="usuarios"><div className="dashboard-content page-content"><div className="page-heading"><div><span className="section-kicker">CONTROLE DE ACESSO</span><h2>Usuários e operadores</h2><p>Administre quem pode acessar e operar o sistema.</p></div><button className="primary-button" onClick={() => { setShowForm(true); setMessage(''); }}><Plus size={16} /> Novo usuário</button></div>{message && <div className="success-message"><CheckCircle2 size={16} /> {message}</div>}<div className="table-panel"><div className="table-wrap"><table><thead><tr><th>NOME</th><th>E-MAIL</th><th>PERFIL</th><th>STATUS</th><th /></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><b>{user.nome}</b></td><td>{user.email}</td><td>{user.perfil === 'ADMINISTRADOR' ? 'Administrador' : 'Operador'}</td><td><span className={`badge ${user.ativo ? 'delivered' : 'pending'}`}>{user.ativo ? 'Ativo' : 'Inativo'}</span></td><td><button className="row-action" onClick={() => toggle(user)}>{user.ativo ? 'Desativar' : 'Ativar'}</button></td></tr>)}</tbody></table></div></div></div>{showForm && <div className="modal-backdrop"><div className="modal-card"><div className="modal-header"><div><span className="section-kicker">ACESSO RESTRITO</span><h2>Criar usuário</h2><p>Senha mínima de 8 caracteres.</p></div><button className="modal-close" onClick={() => setShowForm(false)}>×</button></div><form className="registration-form" onSubmit={save}><label>Nome completo *<input value={form.nome} onChange={event => setForm({ ...form, nome: event.target.value })} required /></label><label>E-mail institucional *<input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /></label><div className="form-grid"><label>Senha temporária *<input type="password" minLength={8} value={form.senha} onChange={event => setForm({ ...form, senha: event.target.value })} required /></label><label>Perfil<select value={form.perfil} onChange={event => setForm({ ...form, perfil: event.target.value as typeof form.perfil })}><option value="OPERADOR">Operador</option><option value="ADMINISTRADOR">Administrador</option></select></label></div><div className="modal-actions"><button type="button" className="cancel-button" onClick={() => setShowForm(false)}>Cancelar</button><button className="primary-button">Criar usuário</button></div></form></div></div>}</PainelShell>;
}
